// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/flowedge.proto

package flowedgepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlowEdge_Communicate_FullMethodName = "/flowedge.FlowEdge/Communicate"
)

// FlowEdgeClient is the client API for FlowEdge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlowEdgeClient interface {
	Communicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamMessage], error)
}

type flowEdgeClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowEdgeClient(cc grpc.ClientConnInterface) FlowEdgeClient {
	return &flowEdgeClient{cc}
}

func (c *flowEdgeClient) Communicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FlowEdge_ServiceDesc.Streams[0], FlowEdge_Communicate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMessage, StreamMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowEdge_CommunicateClient = grpc.BidiStreamingClient[StreamMessage, StreamMessage]

// FlowEdgeServer is the server API for FlowEdge service.
// All implementations must embed UnimplementedFlowEdgeServer
// for forward compatibility.
type FlowEdgeServer interface {
	Communicate(grpc.BidiStreamingServer[StreamMessage, StreamMessage]) error
	mustEmbedUnimplementedFlowEdgeServer()
}

// UnimplementedFlowEdgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlowEdgeServer struct{}

func (UnimplementedFlowEdgeServer) Communicate(grpc.BidiStreamingServer[StreamMessage, StreamMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Communicate not implemented")
}
func (UnimplementedFlowEdgeServer) mustEmbedUnimplementedFlowEdgeServer() {}
func (UnimplementedFlowEdgeServer) testEmbeddedByValue()                  {}

// UnsafeFlowEdgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlowEdgeServer will
// result in compilation errors.
type UnsafeFlowEdgeServer interface {
	mustEmbedUnimplementedFlowEdgeServer()
}

func RegisterFlowEdgeServer(s grpc.ServiceRegistrar, srv FlowEdgeServer) {
	// If the following call pancis, it indicates UnimplementedFlowEdgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlowEdge_ServiceDesc, srv)
}

func _FlowEdge_Communicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FlowEdgeServer).Communicate(&grpc.GenericServerStream[StreamMessage, StreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowEdge_CommunicateServer = grpc.BidiStreamingServer[StreamMessage, StreamMessage]

// FlowEdge_ServiceDesc is the grpc.ServiceDesc for FlowEdge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlowEdge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flowedge.FlowEdge",
	HandlerType: (*FlowEdgeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Communicate",
			Handler:       _FlowEdge_Communicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/flowedge.proto",
}
