// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/flowedge.proto

package flowedgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNKNOWN          MessageType = 0
	MessageType_REGISTER         MessageType = 1
	MessageType_HEARTBEAT        MessageType = 2
	MessageType_EXECUTE_REQUEST  MessageType = 3
	MessageType_EXECUTE_RESPONSE MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "REGISTER",
		2: "HEARTBEAT",
		3: "EXECUTE_REQUEST",
		4: "EXECUTE_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":          0,
		"REGISTER":         1,
		"HEARTBEAT":        2,
		"EXECUTE_REQUEST":  3,
		"EXECUTE_RESPONSE": 4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_flowedge_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_flowedge_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_flowedge_proto_rawDescGZIP(), []int{0}
}

type StreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=flowedge.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*StreamMessage_Register
	//	*StreamMessage_Heartbeat
	//	*StreamMessage_ExecuteRequest
	//	*StreamMessage_ExecuteResponse
	Body          isStreamMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_proto_flowedge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowedge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_proto_flowedge_proto_rawDescGZIP(), []int{0}
}

func (x *StreamMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *StreamMessage) GetBody() isStreamMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *StreamMessage) GetRegister() *RegisterMessage {
	if x != nil {
		if x, ok := x.Body.(*StreamMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *StreamMessage) GetHeartbeat() *HeartbeatMessage {
	if x != nil {
		if x, ok := x.Body.(*StreamMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *StreamMessage) GetExecuteRequest() *ExecuteRequest {
	if x != nil {
		if x, ok := x.Body.(*StreamMessage_ExecuteRequest); ok {
			return x.ExecuteRequest
		}
	}
	return nil
}

func (x *StreamMessage) GetExecuteResponse() *ExecuteResponse {
	if x != nil {
		if x, ok := x.Body.(*StreamMessage_ExecuteResponse); ok {
			return x.ExecuteResponse
		}
	}
	return nil
}

type isStreamMessage_Body interface {
	isStreamMessage_Body()
}

type StreamMessage_Register struct {
	Register *RegisterMessage `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type StreamMessage_Heartbeat struct {
	Heartbeat *HeartbeatMessage `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type StreamMessage_ExecuteRequest struct {
	ExecuteRequest *ExecuteRequest `protobuf:"bytes,4,opt,name=execute_request,json=executeRequest,proto3,oneof"`
}

type StreamMessage_ExecuteResponse struct {
	ExecuteResponse *ExecuteResponse `protobuf:"bytes,5,opt,name=execute_response,json=executeResponse,proto3,oneof"`
}

func (*StreamMessage_Register) isStreamMessage_Body() {}

func (*StreamMessage_Heartbeat) isStreamMessage_Body() {}

func (*StreamMessage_ExecuteRequest) isStreamMessage_Body() {}

func (*StreamMessage_ExecuteResponse) isStreamMessage_Body() {}

type RegisterMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMessage) Reset() {
	*x = RegisterMessage{}
	mi := &file_proto_flowedge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMessage) ProtoMessage() {}

func (x *RegisterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowedge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMessage.ProtoReflect.Descriptor instead.
func (*RegisterMessage) Descriptor() ([]byte, []int) {
	return file_proto_flowedge_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterMessage) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HeartbeatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_proto_flowedge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowedge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_proto_flowedge_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ShellCommand  string                 `protobuf:"bytes,2,opt,name=shell_command,json=shellCommand,proto3" json:"shell_command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_flowedge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowedge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_flowedge_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecuteRequest) GetShellCommand() string {
	if x != nil {
		return x.ShellCommand
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_flowedge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowedge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_flowedge_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_flowedge_proto protoreflect.FileDescriptor

const file_proto_flowedge_proto_rawDesc = "" +
	"\n" +
	"\x14proto/flowedge.proto\x12\bflowedge\"\xc4\x02\n" +
	"\rStreamMessage\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.flowedge.MessageTypeR\x04type\x127\n" +
	"\bregister\x18\x02 \x01(\v2\x19.flowedge.RegisterMessageH\x00R\bregister\x12:\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1a.flowedge.HeartbeatMessageH\x00R\theartbeat\x12C\n" +
	"\x0fexecute_request\x18\x04 \x01(\v2\x18.flowedge.ExecuteRequestH\x00R\x0eexecuteRequest\x12F\n" +
	"\x10execute_response\x18\x05 \x01(\v2\x19.flowedge.ExecuteResponseH\x00R\x0fexecuteResponseB\x06\n" +
	"\x04body\"b\n" +
	"\x0fRegisterMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"K\n" +
	"\x10HeartbeatMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"T\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12#\n" +
	"\rshell_command\x18\x02 \x01(\tR\fshellCommand\"{\n" +
	"\x0fExecuteResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*b\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01\x12\r\n" +
	"\tHEARTBEAT\x10\x02\x12\x13\n" +
	"\x0fEXECUTE_REQUEST\x10\x03\x12\x14\n" +
	"\x10EXECUTE_RESPONSE\x10\x042O\n" +
	"\bFlowEdge\x12C\n" +
	"\vCommunicate\x12\x17.flowedge.StreamMessage\x1a\x17.flowedge.StreamMessage(\x010\x01B\x14Z\x12./proto;flowedgepbb\x06proto3"

var (
	file_proto_flowedge_proto_rawDescOnce sync.Once
	file_proto_flowedge_proto_rawDescData []byte
)

func file_proto_flowedge_proto_rawDescGZIP() []byte {
	file_proto_flowedge_proto_rawDescOnce.Do(func() {
		file_proto_flowedge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_flowedge_proto_rawDesc), len(file_proto_flowedge_proto_rawDesc)))
	})
	return file_proto_flowedge_proto_rawDescData
}

var file_proto_flowedge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_flowedge_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_flowedge_proto_goTypes = []any{
	(MessageType)(0),         // 0: flowedge.MessageType
	(*StreamMessage)(nil),    // 1: flowedge.StreamMessage
	(*RegisterMessage)(nil),  // 2: flowedge.RegisterMessage
	(*HeartbeatMessage)(nil), // 3: flowedge.HeartbeatMessage
	(*ExecuteRequest)(nil),   // 4: flowedge.ExecuteRequest
	(*ExecuteResponse)(nil),  // 5: flowedge.ExecuteResponse
}
var file_proto_flowedge_proto_depIdxs = []int32{
	0, // 0: flowedge.StreamMessage.type:type_name -> flowedge.MessageType
	2, // 1: flowedge.StreamMessage.register:type_name -> flowedge.RegisterMessage
	3, // 2: flowedge.StreamMessage.heartbeat:type_name -> flowedge.HeartbeatMessage
	4, // 3: flowedge.StreamMessage.execute_request:type_name -> flowedge.ExecuteRequest
	5, // 4: flowedge.StreamMessage.execute_response:type_name -> flowedge.ExecuteResponse
	1, // 5: flowedge.FlowEdge.Communicate:input_type -> flowedge.StreamMessage
	1, // 6: flowedge.FlowEdge.Communicate:output_type -> flowedge.StreamMessage
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_flowedge_proto_init() }
func file_proto_flowedge_proto_init() {
	if File_proto_flowedge_proto != nil {
		return
	}
	file_proto_flowedge_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamMessage_Register)(nil),
		(*StreamMessage_Heartbeat)(nil),
		(*StreamMessage_ExecuteRequest)(nil),
		(*StreamMessage_ExecuteResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_flowedge_proto_rawDesc), len(file_proto_flowedge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_flowedge_proto_goTypes,
		DependencyIndexes: file_proto_flowedge_proto_depIdxs,
		EnumInfos:         file_proto_flowedge_proto_enumTypes,
		MessageInfos:      file_proto_flowedge_proto_msgTypes,
	}.Build()
	File_proto_flowedge_proto = out.File
	file_proto_flowedge_proto_goTypes = nil
	file_proto_flowedge_proto_depIdxs = nil
}
